# Generated by Django 5.2.16 on 2026-07-08 21:03

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('client', 'Client')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, help_text='Their role/title at the company', max_length=100)),
                ('sector', models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('finance', 'Finance'), ('legal', 'Legal'), ('technology', 'Technology / Software'), ('automotive', 'Automotive'), ('retail_ecommerce', 'Retail / E-commerce'), ('education', 'Education'), ('government', 'Government / Public Sector'), ('research_academia', 'Research / Academia'), ('other', 'Other')], max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1–10 employees'), ('11-50', '11–50 employees'), ('51-200', '51–200 employees'), ('201-1000', '201–1,000 employees'), ('1000+', '1,000+ employees')], max_length=20)),
                ('company_website', models.URLField(blank=True)),
                ('use_case', models.TextField(blank=True, help_text='What kind of annotation/labeling work are they looking for?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('visa_status', models.CharField(blank=True, choices=[('us_citizen', 'U.S. Citizen'), ('green_card', 'Permanent Resident (Green Card)'), ('h1b', 'H-1B'), ('opt', 'OPT / STEM OPT'), ('tn', 'TN Visa'), ('other_visa', 'Other work visa'), ('not_authorized', 'Not authorized to work in the U.S.'), ('outside_us', 'Outside the U.S. — no visa needed')], max_length=30)),
                ('work_auth_expiry', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('availability_hours', models.PositiveIntegerField(blank=True, help_text='Hours per week', null=True)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('available_days', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('min_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=True)),
                ('notify_project_digest', models.BooleanField(default=True)),
                ('notifications_paused', models.BooleanField(default=False)),
                ('muted_projects', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
